name: PHP

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        laravel-version: ['5.8.*', '^6.0', '^7.0', '^8.0']
        php-versions: ['7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} on Laravel ${{ matrix.laravel-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, xdebug
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer require --no-update --no-interaction "illuminate/support:${{ matrix.laravel-version }}"
          composer update --no-interaction --prefer-dist --no-suggest
      - name: Lint composer.json
        run: composer validate
      - name: Run Tests
        run: composer test:unit
      - name: Run Integration Tests
        if: matrix.laravel-version == '^7.0'
        run: |
            composer require --dev --no-interaction "orchestra/testbench:^5.1"
            composer test:integration
        if: matrix.laravel-version == '^8.0'
            run: |
                composer require --dev --no-interaction "orchestra/testbench:^6.0"
                composer test:integration
